export const siteConfig = {
	name: "movie-library",
	url: "https://movie-library.colidevs.com",
	ogImage: "https://movie-library.colidevs.com/og.jpg",
	description: "movie-library generated by create-coliapp",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
